# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Handoff < Formula
  desc "Transfer knowledge between AI agent sessions"
  homepage "https://github.com/Radixen-Dev/handoff"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Radixen-Dev/handoff/releases/download/v0.1.1/handoff_darwin_amd64.tar.gz"
      sha256 "eb3ca58cddac23b3d8d2e0105aad3fc6d1d8ddc547c1bf8fd8a153f199369888"

      define_method(:install) do
        bin.install "handoff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Radixen-Dev/handoff/releases/download/v0.1.1/handoff_darwin_arm64.tar.gz"
      sha256 "bb767822a1bc6afa31188cdefa9c54596d1fd5b8ac84af8f15f73ddb9cc1d4e8"

      define_method(:install) do
        bin.install "handoff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Radixen-Dev/handoff/releases/download/v0.1.1/handoff_linux_amd64.tar.gz"
      sha256 "7f9aa43a4f3666d7865b4f53a05891ce3dae75e442282629c4690f67d323469b"
      define_method(:install) do
        bin.install "handoff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Radixen-Dev/handoff/releases/download/v0.1.1/handoff_linux_arm64.tar.gz"
      sha256 "11c55f088cc1a27c54bc4f4d46b8d6b0c7945d6ee0d4f1119ca0aeb0658998a5"
      define_method(:install) do
        bin.install "handoff"
      end
    end
  end
end
