# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Handoff < Formula
  desc "Transfer knowledge between AI agent sessions"
  homepage "https://github.com/Dborasik/handoff"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dborasik/handoff/releases/download/v0.1.0/handoff_darwin_amd64.tar.gz"
      sha256 "07e0e751937df511cc7336fb3477992700248cd4369dc1d9ac9ff52894df8070"

      define_method(:install) do
        bin.install "handoff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dborasik/handoff/releases/download/v0.1.0/handoff_darwin_arm64.tar.gz"
      sha256 "41b58868cc5c8f9aea10b0cfefd002b78321652b6858a9fb7229df9330b3113e"

      define_method(:install) do
        bin.install "handoff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dborasik/handoff/releases/download/v0.1.0/handoff_linux_amd64.tar.gz"
      sha256 "e5b714496faf0a83b30780c03246c71f2c8a3b5a610816e7e1a997609b312257"
      define_method(:install) do
        bin.install "handoff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dborasik/handoff/releases/download/v0.1.0/handoff_linux_arm64.tar.gz"
      sha256 "fb1616674f3608bf7ccaee0c3f141edf4b32de4610a694da89c56e2496945a40"
      define_method(:install) do
        bin.install "handoff"
      end
    end
  end
end
